[package]
name = "zyanya-grpc-server"
description = "Zyanya gRPC server"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zyanya-consensus-core.workspace = true
zyanya-core.workspace = true
zyanya-grpc-core.workspace = true
zyanya-notify.workspace = true
zyanya-rpc-core.workspace = true
zyanya-rpc-macros.workspace = true
zyanya-rpc-service.workspace = true
zyanya-utils-tower.workspace = true
zyanya-utils.workspace = true

async-channel.workspace = true
async-stream.workspace = true
async-trait.workspace = true
faster-hex.workspace = true
futures.workspace = true
h2.workspace = true
itertools.workspace = true
log.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
paste.workspace = true
prost.workspace = true
rand.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream.workspace = true
tonic = { workspace = true, features = ["gzip"] }
triggered.workspace = true
uuid.workspace = true
rustls.workspace = true

[dev-dependencies]
zyanya-grpc-client.workspace = true
