[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "zyanya-py"
version = "0.3.17"
description = "Async Python Client for Zyanya GhostDAG L1"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Zyanya Core Developers", email = "dev@zyanya.org" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Security :: Cryptography",
]

[project.urls]
Homepage = "https://github.com/scotthawk-maker/zyanya"
Repository = "https://github.com/scotthawk-maker/zyanya.git"
