[package]
name = "simpa"
description = "Zyanya Network Simulator"
publish = false
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zyanya-alloc.workspace = true            # This changes the global allocator for all of the next dependencies so should be kept first
zyanya-consensus-core.workspace = true
zyanya-consensus-notify.workspace = true
zyanya-consensus.workspace = true
zyanya-core.workspace = true
zyanya-database.workspace = true
zyanya-hashes.workspace = true
zyanya-perf-monitor.workspace = true
zyanya-utils.workspace = true

async-channel.workspace = true
cfg-if.workspace = true
clap.workspace = true
dhat = { workspace = true, optional = true }
futures-util.workspace = true
futures.workspace = true
indexmap.workspace = true
itertools.workspace = true
log.workspace = true
num_cpus.workspace = true
rand_distr.workspace = true
rand.workspace = true
rayon.workspace = true
secp256k1.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }

[features]
heap = ["dhat", "zyanya-alloc/heap"]
semaphore-trace = ["zyanya-utils/semaphore-trace"]
