[package]
name = "zyanya-index-processor"
description = "Zyanya index processor"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zyanya-consensus-core.workspace = true
zyanya-consensus-notify.workspace = true
zyanya-consensusmanager.workspace = true
zyanya-core.workspace = true
zyanya-database.workspace = true
zyanya-hashes.workspace = true
zyanya-index-core.workspace = true
zyanya-notify.workspace = true
zyanya-utils.workspace = true
zyanya-utxoindex.workspace = true

async-channel.workspace = true
async-trait.workspace = true
derive_more.workspace = true
futures.workspace = true
log.workspace = true
paste.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [ "rt-multi-thread", "macros", "signal" ]}
triggered.workspace = true

[dev-dependencies]
zyanya-consensus.workspace = true
parking_lot.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
rand = {workspace = true,  features = [ "small_rng" ]}
