[package]
name = "zyanya-consensusmanager"
description = "Zyanya consensus library"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
duration-string.workspace = true
futures-util.workspace = true
futures.workspace = true
itertools.workspace = true
zyanya-addresses.workspace=true
zyanya-consensus-core.workspace = true
zyanya-consensus-notify.workspace = true
zyanya-core.workspace = true
zyanya-utils.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
tokio.workspace = true
