[package]
name = "zyanya-wrpc-proxy"
description = "Zyanya wRPC to gRPC proxy"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
clap.workspace = true
zyanya-consensus-core.workspace = true
zyanya-grpc-client.workspace = true
zyanya-rpc-core.workspace = true
zyanya-rpc-macros.workspace = true
zyanya-wrpc-server.workspace = true
num_cpus.workspace = true
thiserror.workspace = true
tokio.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
workflow-rpc.workspace = true

[package.metadata.emanate.build]
folder = "setup"
