[package]
name = "zyanyad"
description = "Zyanya full node daemon"
keywords = ["zyanya", "blockdag"]
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "zyanyad_lib"
crate-type = ["cdylib", "lib"]

[dependencies]
zyanya-alloc.workspace = true # This changes the global allocator for all of the next dependencies so should be kept first

zyanya-addresses.workspace = true
zyanya-addressmanager.workspace = true
zyanya-consensus-core.workspace = true
zyanya-consensus-notify.workspace = true
zyanya-consensus.workspace = true
zyanya-consensusmanager.workspace = true
zyanya-core.workspace = true
zyanya-database.workspace = true
zyanya-grpc-server.workspace = true
zyanya-hashes.workspace = true
zyanya-index-processor.workspace = true
zyanya-mining.workspace = true
zyanya-notify.workspace = true
zyanya-p2p-flows.workspace = true
zyanya-perf-monitor.workspace = true
zyanya-rpc-core.workspace = true
zyanya-rpc-service.workspace = true
zyanya-txscript.workspace = true
zyanya-utils.workspace = true
zyanya-utils-tower.workspace = true
zyanya-utxoindex.workspace = true
zyanya-wrpc-server.workspace = true

async-channel.workspace = true
cfg-if.workspace = true
clap.workspace = true
dhat = { workspace = true, optional = true }
dirs.workspace = true
futures-util.workspace = true
itertools.workspace = true
log.workspace = true
num_cpus.workspace = true
rand.workspace = true
rayon.workspace = true
rocksdb.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }
workflow-log.workspace = true

toml = "0.8.10"
serde_with = "3.7.0"

[features]
heap = ["dhat", "zyanya-alloc/heap"]
devnet-prealloc = ["zyanya-consensus/devnet-prealloc"]
semaphore-trace = ["zyanya-utils/semaphore-trace"]
