#!/bin/bash
# This script builds the Rusty Zyanya WASM32 SDK release.

# make the script fail for any failed command
set -e

rm -rf release/*
rm -rf web/*
rm -rf nodejs/*
rm -rf docs/*
rm -rf examples/nodejs/typescript/lib

mkdir -p release/zyanya-wasm32-sdk/web
mkdir -p release/zyanya-wasm32-sdk/nodejs
mkdir -p release/zyanya-wasm32-sdk/docs

# pushd .
# cd ../rpc/wrpc/wasm
# wasm-pack build --target web --out-name zyanya-rpc --out-dir web/zyanya-rpc --features wasm32-sdk $@
# popd

wasm-pack build --weak-refs --target web --out-name zyanya --out-dir web/zyanya-keygen --features wasm32-keygen $@
wasm-pack build --weak-refs --dev --target web --out-name zyanya --out-dir web/zyanya-keygen-dev --features wasm32-keygen $@

wasm-pack build --weak-refs --target web --out-name zyanya --out-dir web/zyanya-rpc --features wasm32-rpc $@
wasm-pack build --weak-refs --dev --target web --out-name zyanya --out-dir web/zyanya-rpc-dev --features wasm32-rpc $@

wasm-pack build --weak-refs --target web --out-name zyanya --out-dir web/zyanya-core --features wasm32-core $@
wasm-pack build --weak-refs --dev --target web --out-name zyanya --out-dir web/zyanya-core-dev --features wasm32-core $@

wasm-pack build --weak-refs --target web --out-name zyanya --out-dir web/zyanya --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target web --out-name zyanya --out-dir web/zyanya-dev --features wasm32-sdk $@

wasm-pack build --weak-refs --target nodejs --out-name zyanya --out-dir nodejs/zyanya --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target nodejs --out-name zyanya --out-dir nodejs/zyanya-dev --features wasm32-sdk $@

# wasm-pack build --target web --dev --out-name zyanya --out-dir build/docs/zyanya --features wasm32-sdk $@
typedoc --name "Zyanya WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/zyanya-keygen ./build/docs/zyanya-keygen.ts
typedoc --name "Zyanya WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/zyanya-rpc ./build/docs/zyanya-rpc.ts
typedoc --name "Zyanya WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/zyanya-core ./build/docs/zyanya-core.ts
typedoc --name "Zyanya WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/zyanya ./build/docs/zyanya.ts

# cp -r ../rpc/wrpc/wasm/web/zyanya-rpc release/zyanya-wasm32-sdk/web/zyanya-rpc
cp -r web/zyanya-keygen release/zyanya-wasm32-sdk/web/zyanya-keygen
cp -r web/zyanya-keygen-dev release/zyanya-wasm32-sdk/web/zyanya-keygen-dev

cp -r web/zyanya-rpc release/zyanya-wasm32-sdk/web/zyanya-rpc
cp -r web/zyanya-rpc-dev release/zyanya-wasm32-sdk/web/zyanya-rpc-dev

cp -r web/zyanya-core release/zyanya-wasm32-sdk/web/zyanya-core
cp -r web/zyanya-core-dev release/zyanya-wasm32-sdk/web/zyanya-core-dev

cp -r web/zyanya release/zyanya-wasm32-sdk/web/zyanya
cp -r web/zyanya-dev release/zyanya-wasm32-sdk/web/zyanya-dev

cp -r nodejs/zyanya release/zyanya-wasm32-sdk/nodejs/zyanya
cp -r nodejs/zyanya-dev release/zyanya-wasm32-sdk/nodejs/zyanya-dev

cp -r docs/zyanya-keygen release/zyanya-wasm32-sdk/docs/zyanya-keygen
cp -r docs/zyanya-rpc release/zyanya-wasm32-sdk/docs/zyanya-rpc
cp -r docs/zyanya-core release/zyanya-wasm32-sdk/docs/zyanya-core
cp -r docs/zyanya release/zyanya-wasm32-sdk/docs/zyanya

mkdir -p release/zyanya-wasm32-sdk/examples/data
cp -r examples/data/.gitignore release/zyanya-wasm32-sdk/examples/data/.gitignore
cp -r examples/nodejs release/zyanya-wasm32-sdk/examples/
cp -r examples/web release/zyanya-wasm32-sdk/examples/
cp -r examples/init.js release/zyanya-wasm32-sdk/examples/
cp -r examples/jsconfig.json release/zyanya-wasm32-sdk/examples/
cp -r examples/package.json release/zyanya-wasm32-sdk/examples/

pushd .
cd release/zyanya-wasm32-sdk/examples
npm install
popd

# tsc release/zyanya-wasm32-sdk/examples/nodejs/typescript/

cp index.html release/zyanya-wasm32-sdk/index.html
cp README.md release/zyanya-wasm32-sdk/README.md
cp CHANGELOG.md release/zyanya-wasm32-sdk/CHANGELOG.md
cp LICENSE release/zyanya-wasm32-sdk/LICENSE

node build/package-sizes.js
cp package-sizes.js release/zyanya-wasm32-sdk/package-sizes.js

pushd .
cd release
zip -q -r zyanya-wasm32-sdk.zip zyanya-wasm32-sdk
popd

