[package]
name = "zyanya-wrpc-server"
description = "Zyanya wRPC server"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
async-trait.workspace = true
borsh = { workspace = true, features = ["rc"] }
futures.workspace = true
zyanya-consensus-core.workspace = true
zyanya-core.workspace = true
zyanya-grpc-client.workspace = true
zyanya-notify.workspace = true
zyanya-rpc-core.workspace = true
zyanya-rpc-macros.workspace = true
zyanya-rpc-service.workspace = true
zyanya-utils.workspace = true
log.workspace = true
num_cpus.workspace = true
paste.workspace = true
serde = { workspace = true, features = ["rc"] }
thiserror.workspace = true
tokio.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
workflow-rpc.workspace = true
workflow-serializer.workspace = true
rustls.workspace = true
