[package]
name = "zyanya-consensus"
description = "Zyanya consensus library"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arc-swap.workspace = true
async-channel.workspace = true
bincode.workspace = true
crossbeam-channel.workspace = true
faster-hex.workspace = true
futures-util.workspace = true
indexmap.workspace = true
itertools.workspace = true
zyanya-addresses.workspace = true
zyanya-consensus-core.workspace = true
zyanya-consensus-notify.workspace = true
zyanya-consensusmanager.workspace = true
zyanya-core.workspace = true
zyanya-database.workspace = true
zyanya-hashes.workspace = true
zyanya-math.workspace = true
zyanya-merkle.workspace = true
zyanya-muhash.workspace = true
zyanya-notify.workspace = true
zyanya-pow.workspace = true
zyanya-txscript.workspace = true
zyanya-txscript-errors.workspace = true
zyanya-utils.workspace = true
zyanya-vm.workspace = true
log.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
rayon.workspace = true
rocksdb.workspace = true
secp256k1.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tokio.workspace = true

rand = { workspace = true, features = ["small_rng"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }

[dev-dependencies]
criterion.workspace = true
serde_json.workspace = true
flate2.workspace = true
rand_distr.workspace = true
zyanya-txscript-errors.workspace = true
zyanya-addresses.workspace = true

[[bench]]
name = "parallel_muhash"
harness = false

[[bench]]
name = "check_scripts"
harness = false

[features]
html_reports = []
devnet-prealloc = ["zyanya-consensus-core/devnet-prealloc"]
