[package]
name = "zyanya-mining"
description = "Zyanya mining"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zyanya-addresses.workspace = true
zyanya-consensus-core.workspace = true
zyanya-consensusmanager.workspace = true
zyanya-core.workspace = true
zyanya-hashes.workspace = true
zyanya-mining-errors.workspace = true
zyanya-muhash.workspace = true
zyanya-txscript.workspace = true
zyanya-utils.workspace = true

futures-util.workspace = true
itertools.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
serde.workspace = true
smallvec.workspace = true
sweep-bptree = "0.4.1"
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }

[dev-dependencies]
zyanya-txscript.workspace = true
criterion.workspace = true
secp256k1.workspace = true

[[bench]]
name = "bench"
harness = false
