[package]
name = "zyanya-explorer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zyanya-grpc-client = { workspace = true }
zyanya-rpc-core = { workspace = true }
zyanya-hashes = { workspace = true }
zyanya-utils = { workspace = true }
zyanya-vm = { workspace = true }
zyanya-consensus-core = { workspace = true }
zyanya-addresses = { workspace = true }
zyanya-txscript = { workspace = true }

tokio = { workspace = true, features = ["sync", "rt-multi-thread", "net", "macros"] }
axum = "0.7.9"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
socket2 = "0.5.5"
