[package]
name = "zyanya-connectionmanager"
description = "Zyanya connection manager"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
duration-string.workspace = true
futures-util.workspace = true
itertools.workspace = true
zyanya-addressmanager.workspace = true
zyanya-core.workspace = true
zyanya-p2p-lib.workspace = true
zyanya-utils.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
tokio.workspace = true
